# Generated by Django 4.2.7 on 2025-01-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_remove_pessoa_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('idade', models.IntegerField()),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
