# Generated by Django 4.2.7 on 2025-01-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_contato_delete_pessoa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contato',
            new_name='Pessoa',
        ),
    ]
